= Questioning Privacy through Public Personal Email

:hp-tags: Email, Privacy, Open Source

[.lead]
After watching an interview with Fred Trotter on the EdX course link:https://www.edx.org/course/medicine-digital-age-ricex-meddigx-0[Medicine in the Digital Age], I began thinking about why privacy is important. Fred discussed the ironic fact that a hospital gown the antithesis of privacy, but providers are often prevented from sharing important medical information due to concerns about privacy (see tweet below). 

+++++
<center>
<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr">Ludicrous to tell a pt in a gown that our job is to protect his privacy <a href="https://twitter.com/fredtrotter">@fredtrotter</a> <a href="https://twitter.com/hashtag/MedX?src=hash">#MedX</a> <a href="https://twitter.com/hashtag/HIPAA?src=hash">#HIPAA</a> <a href="https://twitter.com/hashtag/Healthcare?src=hash">#Healthcare</a> <a href="https://twitter.com/hashtag/data?src=hash">#data</a> <a href="http://t.co/iQYBXM1CGD">pic.twitter.com/iQYBXM1CGD</a></p>&mdash; Hugo Campos (@HugoOC) <a href="https://twitter.com/HugoOC/status/508286212092612609">September 6, 2014</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
</center>
+++++

In healthcare settings this loss of privacy is necessary to perform many medical procedures – consider a procedure which requires anesthesia (such as a colonoscopy); pretty much all physical privacy is lost. We assume that privacy is important except when it’s necessary to give it up, but could we benefit from questioning our default assumption that more privacy is always better?

== Why Privacy is Important


One reason privacy is important is because information can be used to discriminate against individuals in certain groups. For example, before the Americans with Disabilities Act of 1990 an individual could be fired for having a disability, including HIV/AIDS, after an employer discovered this private information. Currently, many states still do not have legislation which protects individuals from employment discrimination based on link:http://www.hrc.org/resources/entry/employment-non-discrimination-act[sexual orientation or gender identity]. By keeping certain information private, individuals can retain their job, even if their employer discriminates against certain groups to which they belong.

++++
<div class="sidebarblock" style="border:solid; margin:10pt; padding:10pt>
<div class="content">
<div class="title"><h4><center>Extending Privacy</h4></center></div>
<p>
Let’s consider the benefits of extending privacy on a characteristic which is relatively difficult for certain groups to hide: sex at birth. For the majority of individuals sex at birth and gender identity are the same, and (at least in English) common names identify the sex of an individual. Would it be beneficial to keep sex at birth private?</p>

<p>The <a href="http://www.vox.com/cards/gender-wage-gap-men-women-pay">gender wage gap</a> is well known, and one contributing factor of the wage gap is the fact the women consistently negotiate lower salaries than men. <a href="http://tpr.org/post/why-women-dont-ask-more-money">Research</a> suggests, however, not that women are worse negotiators, but they are intuitively aware of social norms that prevent them from negotiating: the fact that women who negotiate fiercely are unwelcome in certain business environments discourages women from negotiating. Women understood that if they did negotiate, they might be penalized for this socially unacceptable behavior. If somehow women were able to keep their sex private, they would no longer need to be concerned about the social norms which force them to negotiate less.</p>

<p>Would this solve the problem?</p>
</div>
</div>

++++


Privacy is also important because our identity could not be secured otherwise. From banking account information to email, we currently need privacy to ensure that our identities (and financial assets) remain secure.

Are there other reasons that privacy is important today? 



== Drawbacks of Privacy
A particularly insightful paragraph from Wikipedia discusses the drawbacks of privacy as part of the decision-action process: 

.Privacy
[quote, In Wikipedia&#44 The Free Encyclopedia., Retrieved 03:52&#44 June 12&#44 2015]
____
Various types of personal information are often associated with privacy concerns. Information plays an important role in the decision-action process, which can lead to problems in terms of privacy and availability. First, it allows people to see all the options and alternatives available. Secondly, it allows people to choose which of the options would be best for a certain situation...
____

Privacy prevents information flow and without information, individuals can not choose the best option for certain situations. The Affordable Care Act reduced privacy (increased transparency) of healthcare costs and will increase the ability of consumers to choose the most cost effective health care solution. Hopefully this will reduce overall link:https://www.wm.edu/as/publicpolicy/wm_policy_review/Archives/Volume%204%20Issue%202/MuirAlessiKing_s13f.pdf[healthcare costs] in the US.

Another drawback of privacy comes from the area of healthcare research (which is why I am primarily interested in it). If healthcare data was not private, researchers could link together an unimaginable number of data sets and investigate a wide range of diseases. The number of research questions scientists could address and the strength of the analyses would no doubt lead to a healthier nation and world.

Having lived in Asia for several years, I wonder if this idea of privacy would have developed in more communal cultures if the strong western influence was absent. Individuals from more communal cultures may find it easier to understand that sacrifice of privacy or individual identity can lead to a stronger community.  

== Email Privacy
As a former government employee, I was aware that all my work emails might one day be publicly available (although the feasibility of accessing these emails is questionable). This policy was also recently highlighted in link:http://www.nationalreview.com/article/414773/latest-clinton-scandal-quintessentially-hillary-charles-c-w-cooke[Hillary Clinton's email scandal].

++++
<center>
<div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:445px;"><div style="overflow:hidden;position:relative;height:0;padding:66.666667% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/465796192?et=P9OJ1QelRuRuruZFEpJdGQ&viewMoreLink=off&sig=JQr-_f_iys96_uDDpPd0IGewve96FU_Chv0YgKKi98I=" width="445" height="297" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/465796192" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div></center>
<br>
++++



In fact, I encouraged my former management team to adopt an open email system (see link:https://stripe.com/blog/email-transparency[Stripe]) which would hopefully lead to faster information flow and fewer meetings. I suggested an opt-in system, so an email which an employee wanted to be private, could remain so, but that the majority of emails would be archived in a public data base that could be sorted and searchable. This would be an enormous trove of data that could easily be accessed.

This thought process led me to my current idea: public personal email. As a proponent of transparency and openness, I wonder how making my personal email public would impact my life. In the era of the smartphone, as emails and tweets are posted 24 hours/day, the lines between work-time and personal-time are blurring. More and more of individuals’ lives are becoming public and as we post more and more (and even live link:https://meerkatapp.co/[stream our lives]) we seem to be unintentionally questioning the usefulness of privacy. link:https://luxsci.com/blog/the-case-for-email-security.html[Email is insecure] already, so would making it public be such an issue? I intend to explore the practical implications of public personal email in my next blog post.
